language: ruby
rvm:
  - ruby-1.8.7
  - ruby-1.9.2
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-head

script: 'bundle exec rspec'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rpm

notifications:
  email: false
